// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZCyxV3wRjorZ8IXABZr0TjCGS6sibpkc',
    appId: '1:1006336912262:web:777191783845be313fda07',
    messagingSenderId: '1006336912262',
    projectId: 'expensenote-94a2f',
    authDomain: 'expensenote-94a2f.firebaseapp.com',
    storageBucket: 'expensenote-94a2f.appspot.com',
    measurementId: 'G-E6ZM55MJQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3J0piueYewq8nA5fw4zoSCqSRdIZbM4k',
    appId: '1:1006336912262:android:037572f0bede46023fda07',
    messagingSenderId: '1006336912262',
    projectId: 'expensenote-94a2f',
    storageBucket: 'expensenote-94a2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1-K5_ajpsZlQ0TZRreq7AwKB7VvNsWH8',
    appId: '1:1006336912262:ios:c754db4024abe94a3fda07',
    messagingSenderId: '1006336912262',
    projectId: 'expensenote-94a2f',
    storageBucket: 'expensenote-94a2f.appspot.com',
    iosBundleId: 'com.example.expensenote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1-K5_ajpsZlQ0TZRreq7AwKB7VvNsWH8',
    appId: '1:1006336912262:ios:c754db4024abe94a3fda07',
    messagingSenderId: '1006336912262',
    projectId: 'expensenote-94a2f',
    storageBucket: 'expensenote-94a2f.appspot.com',
    iosBundleId: 'com.example.expensenote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZCyxV3wRjorZ8IXABZr0TjCGS6sibpkc',
    appId: '1:1006336912262:web:8033fed7ecd78aba3fda07',
    messagingSenderId: '1006336912262',
    projectId: 'expensenote-94a2f',
    authDomain: 'expensenote-94a2f.firebaseapp.com',
    storageBucket: 'expensenote-94a2f.appspot.com',
    measurementId: 'G-HN6W1BTN4J',
  );
}
